webtalk_init -webtalk_dir D:/Tamara/Dokumente/study/4th Semester/spro4-em/vivado/sine_generator/sine_generator.sim/sim_1/impl/timing/xsim/xsim.dir/frequency_select_test_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr  3 12:02:24 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2117270" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9c7a4dda-9fa3-4695-aa05-14a3cd53624a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2323e59728ad4756b01329fb10e00e57" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "26 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 480063454 -regid "" -xml D:/Tamara/Dokumente/study/4th Semester/spro4-em/vivado/sine_generator/sine_generator.sim/sim_1/impl/timing/xsim/xsim.dir/frequency_select_test_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/Tamara/Dokumente/study/4th Semester/spro4-em/vivado/sine_generator/sine_generator.sim/sim_1/impl/timing/xsim/xsim.dir/frequency_select_test_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/Tamara/Dokumente/study/4th Semester/spro4-em/vivado/sine_generator/sine_generator.sim/sim_1/impl/timing/xsim/xsim.dir/frequency_select_test_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
